# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    ignore:
      # Ignore versions that are incompatible with Python 3.7
      - dependency-name: setuptools
        versions:
          - ">=68.1"
      - dependency-name: pytest-randomly
        versions:
          - ">=3.13"
      - dependency-name: pytest-cov
        versions:
          - ">=5"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
