additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false
  httpUserAgent: zamzar-python-v1
  infoName: Zamzar
  packageName: zamzar_sdk
  packageUrl: https://github.com/zamzar/zamzar-python
  projectName: zamzar-sdk

globalProperties:
  apiTests: false
  modelTests: false