name: test

on:
  pull_request

jobs:
  test:
    name: Run tests for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"  # Oldest supported
          - "3.14" # Latest release

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start containers
        run: make up

      - name: Run tests
        run: make test